# Generated by Django 4.0.5 on 2022-07-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0004_rename_complete_order_ordered_remove_order_costumer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
