# Generated by Django 4.0.5 on 2022-07-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0006_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='ecomm.orderitem'),
            preserve_default=False,
        ),
    ]
