# Generated by Django 4.0.5 on 2022-07-15 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0008_alter_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='motorcycle', to='ecomm.company'),
        ),
    ]
