# Generated by Django 4.0.5 on 2022-08-30 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0011_motorcycle_anatomy_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
