# Generated by Django 4.0.5 on 2022-11-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0014_alter_product_category_alter_product_motorcycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
