# Generated by Django 4.0.5 on 2022-11-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0015_alter_motorcycle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
