# Generated by Django 4.0.5 on 2022-11-04 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0016_alter_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=255)),
                ('costumer_name', models.CharField(max_length=255)),
                ('cashier_name', models.CharField(max_length=255)),
                ('item_list', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logs', models.CharField(max_length=255)),
                ('cashier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomm.staffs')),
                ('transaction_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecomm.transaction')),
            ],
        ),
    ]
