# Generated by Django 4.0.5 on 2022-11-29 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0018_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='proccessed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomm.staffs'),
        ),
    ]
